#!/bin/sh
#
# /etc/init.d/smokeping
#
### BEGIN INIT INFO
# Provides:          lm50client
# Required-Start:    $network
# Should-Start:
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the lm50client daemon
# Description:       LM50client is a logging daemon that queries the
#                    LM50 device and writes the data into RRD files.
#                    This script is used to start or stop the daemon.
### END INIT INFO
#

set -e

# Source LSB init functions
. /lib/lsb/init-functions

DAEMON=/usr/local/bin/lm50client
NAME=lm50client
DESC="lm50client logger daemon"
CONFIG=/etc/lm50client/lm50client.cnf
DAEMON_ARGS="-c $CONFIG"

# LC_ALL prevents resetting LC_NUMERIC which in turn interferes
# with Smokeping internal regexps matching floating point numbers
unset LC_ALL

# Check whether the binary is still present:
test -f "$DAEMON" || exit 0

check_config () {
    # Check whether the configuration file is available
    if [ ! -r "$CONFIG" ]
    then
        log_progress_msg "($CONFIG does not exist)"
        log_end_msg 6 # program is not configured
        exit 6
    fi
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" $NAME
        check_config
        set +e
        start-stop-daemon --start --quiet --exec $DAEMON --oknodo \
            -- $DAEMON_ARGS \
            | logger -p daemon.notice -t $NAME
        STATUS=$?
        set -e

        log_end_msg $STATUS
        exit $STATUS
        ;;


    stop)
        log_daemon_msg "Shutting down $DESC" $NAME
        set +e
        start-stop-daemon --stop --quiet --exec $DAEMON --oknodo --retry 3
        STATUS=$?
        set -e

        log_end_msg $STATUS
        exit $STATUS
        ;;


    restart)
        # Restart service (if running) or start service
        $0 stop
        $0 start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
